name = "masjid-tv"
compatibility_date = "2026-07-26"
pages_build_output_dir = "."

[observability]
enabled = true
head_sampling_rate = 1

[[d1_databases]]
binding = "DB"
database_name = "masjid-db"
database_id = "6d2e8459-901f-4f2b-be31-086cc425ee72"
